name: similar-repositories-env
channels:
  - defaults
  - anaconda
  - pytorch
dependencies:
  - python=3.7
  - pygments
  - joblib
  - tqdm
  - cython
  - numpy
  - faiss-cpu
  - pytest
  - pip
  - pip:
    - PyStemmer
    - tree_sitter
    - gdown
