name: Docker CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:

  push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        name: Build & push Docker image
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: egorbogomolov/similar-repositories
          tag_with_ref: true
          tag_with_sha: true

  verify-image-unix:

    needs: push

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull docker image
      run: docker pull egorbogomolov/similar-repositories:latest
    - name: Run the tool from docker
      run: docker run \
          --mount type=bind,source=`pwd`/input_examples,target=/input_examples/ \
          --mount type=bind,source=`pwd`/output,target=/output/ \
          --mount type=bind,source=`pwd`/data,target=/data \
          egorbogomolov/similar-repositories:latest -i input_examples/input.txt -o output/examples_output/
